# Generated by Django 5.0.1 on 2024-02-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
