# Generated by Django 5.0.1 on 2024-02-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0002_alter_dashboarddata_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='title',
            field=models.CharField(max_length=800),
        ),
    ]
