# Generated by Django 5.0.1 on 2024-02-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0005_alter_dashboarddata_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='region',
            field=models.CharField(max_length=500),
        ),
    ]
