# Generated by Django 5.0.1 on 2024-02-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0006_alter_dashboarddata_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='region',
            field=models.CharField(max_length=300),
        ),
    ]
